[phases.setup]
cmds = [
    "python -m venv venv",
    "source venv/bin/activate"
]

[phases.install]
cmds = [
    "source venv/bin/activate && pip install --upgrade pip",
    "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "source venv/bin/activate && python app.py"
env = [
    "FLASK_APP=app.py",
    "FLASK_ENV=production"
]
